name = "vanes-ai-v2-forex"
main = "src/index.js"
compatibility_date = "2026-09-19"

[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true
